### ISSUE TITLE
Error when execute command and reboot Ubuntu

### ISSUE THREAD

**Issue by ebolanoso** [kojibhy/cuckoo-yara-auto#2]
Hi, how you doing?

I have an error when I execute this command and reboot UBUNTU 17.10, ubuntu don't start. 

apt install python gdebi tesseract-ocr python-pip python-dev libffi-dev libssl-dev libfuzzy-dev python-virtualenv python-setuptools libjpeg-dev zlib1g-dev swig virtualbox virtualbox-guest-x11 mongodb -y

What can produce it?

Regards.

**Comment by kojibhy** [comment]
I am sure issues with VirtualBox and Linux kernel, please follow install guide from VirtualBox official website.

if you want to see more info on boot:
edit this file:  nano /etc/default/grub
line: GRUB_CMDLINE_LINUX_DEFAULT=""

**Comment by ebolanoso** [comment]
Thanks, everything ok now.
