### ISSUE TITLE
Failed to connect to 0.0.0.0 port 9200: Connection refused (Elasticsearch)

### ISSUE THREAD

**Issue by ebolanoso** [kojibhy/cuckoo-yara-auto#3]
I have this issue when I try to install and start Elasticsearch based on your "Cuckoo Installation Guide", can you help me?

I'm using Cuckoo Sandbox 2.0.6 on Ubuntu 18.04.1 LTS

This is the log:

root@ubuntu:/home/csma/Downloads# gdebi elasticsearch-5.6.8.deb
Reading package lists... Done
Building dependency tree        
Reading state information... Done
Reading state information... Done

Elasticsearch is a distributed RESTful search engine built for the cloud. Reference documentation can be found at https://www.elastic.co/guide/en/elasticsearch/reference/current/index.html and the 'Elasticsearch: The Definitive Guide' book can be found at https://www.elastic.co/guide/en/elasticsearch/guide/current/index.html
 Elasticsearch subproject :distribution:deb
Do you want to install the software package? [y/N]:y
(Reading database ... 190002 files and directories currently installed.)
Preparing to unpack elasticsearch-5.6.8.deb ...
Unpacking elasticsearch (5.6.8) over (5.6.8) ...
Setting up elasticsearch (5.6.8) ...
Processing triggers for ureadahead (0.100.0-20) ...
Processing triggers for systemd (237-3ubuntu10.3) ...
root@ubuntu:/home/csma/Downloads# usermod -a -G elasticsearch cuckoo
root@ubuntu:/home/csma/Downloads# cd
root@ubuntu:~# cd /home/cuckoo
root@ubuntu:/home/cuckoo# cd /etc/
root@ubuntu:/etc# nano elasticsearch/elasticsearch.yml

Edit
          cluster.name: es-cuckoo 
          node.name: es-node-n1
          bootstrap.mlockall: true
          network.bind_host: 0.0.0.0

root@ubuntu:/etc#    chown -R elasticsearch:elasticsearch /var/lib/elasticsearch
root@ubuntu:/etc#    chown -R elasticsearch:elasticsearch /var/run/elasticsearch
root@ubuntu:/etc#    chown -R elasticsearch:elasticsearch /etc/elasticsearch
root@ubuntu:/etc# service elasticsearch start
root@ubuntu:/etc# service elasticsearch status
● elasticsearch.service - Elasticsearch
   Loaded: loaded (/usr/lib/systemd/system/elasticsearch.service; disabled; ven
  Drop-In: /etc/systemd/system/elasticsearch.service.d
           └─override.conf
   Active: active (running) since Sun 2018-08-19 10:38:58 PDT; 3s ago
     Docs: http://www.elastic.co
  Process: 2047 ExecStartPre=/usr/share/elasticsearch/bin/elasticsearch-systemd
 Main PID: 2048 (java)
    Tasks: 6 (limit: 9473)
   CGroup: /system.slice/elasticsearch.service
           └─2048 /usr/bin/java -Xms2g -Xmx2g -XX:+UseConcMarkSweepGC -XX:CMSIn

Aug 19 10:38:58 ubuntu systemd[1]: Starting Elasticsearch...
Aug 19 10:38:58 ubuntu systemd[1]: Started Elasticsearch.

root@ubuntu:/etc# curl localhost:9200
curl: (7) Failed to connect to localhost port 9200: Connection refused

**Comment by ebolanoso** [comment]
Any idea? help please

**Comment by kojibhy** [comment]
hi, 
in /etc/default/elasticsearch, make sure these are un-commented:

START_DAEMON=true
ES_USER=elasticsearch
ES_GROUP=elasticsearch
LOG_DIR=/var/log/elasticsearch
DATA_DIR=/var/lib/elasticsearch
WORK_DIR=/tmp/elasticsearch
CONF_DIR=/etc/elasticsearch
CONF_FILE=/etc/elasticsearch/elasticsearch.yml
RESTART_ON_UPGRADE=true
make sure /var/lib/elasticsearch is owned by elasticsearch user:

command: chown -R elasticsearch:elasticsearch /var/lib/elasticsearch/
